### ISSUE TITLE
/idesh/gosu_entrypoint.sh: line 34: exec: smartide: not found

### ISSUE THREAD

**Issue by JJLAAA** [SmartIDE/SmartIDE#25]
镜像：`registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-jetbrains-idea:2021.2.3-openjdk-11-jdk-2081`
容器日志为：`/idesh/gosu_entrypoint.sh: line 34: exec: smartide: not found`

**Comment by ups216** [comment]
请问你是如何启动的这个容器？是通过smartide cli吗？

**Comment by JJLAAA** [comment]
> 请问你是如何启动的这个容器？是通过smartide cli吗？

是的 
`smartide start --host 1 git@gitee.com:diegoGeek/blog-submitter.git`
这是我的配置文件
```yaml
version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-java-idea
    ports:
      tools-webide-idea: 6800
      tools-ssh: 6822
      apps-application: 3001
    ide-type: jb-projector
    volumes: 
      git-config: true
      ssh-key: true
  services:
    smartide-template-java-idea:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-jetbrains-idea:2021.2.3-openjdk-11-jdk-2081
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      ports:
        - 6822:22
        - 6800:8887
        - 3001:3001
      volumes:
        - .:/home/project
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true
```
