### ISSUE TITLE
cli - gitlab ci extension

### ISSUE THREAD

**Issue by ups216** [SmartIDE/SmartIDE#30]
allow user to trigger a smartide-cli task to create a remote workspace, this is useful when you want deploy a dev/test environment with a specific codebase version.

here is a gitlab-smartide-cli-ci.yml sample

```yaml
stages:
    - smartide

smartide_start:
    stage: dev-env-start
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-cli
    script:
        - smartide start --mode=server --host <address-ip> --username <ssh-user> --password <ssh-password> <git-url>
```

consider pass in the following parameters:
- <host-address>
- <username>
- <password>
- <git-url>: support https/ssh
- <git-branch-name>: actually a <git-ref>, so you can use commit-id, tag, branch
- <callback-api-address>: smartide-cli is able to send back a json with all data about the workspace.
